-- Run this entire file once in Supabase > SQL Editor.
create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  province text not null check (province ~ '^[a-z0-9-]+$'),
  title text not null check (char_length(trim(title)) between 1 and 80),
  artist text not null check (char_length(trim(artist)) between 1 and 80),
  link text check (link is null or char_length(link) <= 500),
  submitted_by text not null check (char_length(trim(submitted_by)) between 1 and 50),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.songs add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.songs enable row level security;
drop policy if exists "Public can read songs" on public.songs;
drop policy if exists "Users can submit songs" on public.songs;
drop policy if exists "Public can submit songs" on public.songs;
create policy "Public can read songs" on public.songs for select to anon, authenticated using (true);
create policy "Users can submit songs" on public.songs for insert to authenticated
with check (auth.uid() = user_id);

-- Server-side rate limit: one song per account every 60 seconds.
create or replace function public.limit_song_submissions()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if exists (
    select 1 from public.songs
    where user_id = new.user_id and created_at > now() - interval '60 seconds'
  ) then
    raise exception 'Please wait before submitting another song';
  end if;
  return new;
end;
$$;
drop trigger if exists enforce_song_rate_limit on public.songs;
create trigger enforce_song_rate_limit before insert on public.songs
for each row execute function public.limit_song_submissions();

create table if not exists public.song_likes (
  song_id bigint not null references public.songs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (song_id, user_id)
);
alter table public.song_likes enable row level security;
drop policy if exists "Public can read likes" on public.song_likes;
drop policy if exists "Users manage own likes" on public.song_likes;
create policy "Public can read likes" on public.song_likes for select to anon, authenticated using (true);
create policy "Users manage own likes" on public.song_likes for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists songs_created_at_idx on public.songs(created_at desc);
create index if not exists song_likes_song_id_idx on public.song_likes(song_id);
grant usage on schema public to anon, authenticated;
grant select on public.songs, public.song_likes to anon, authenticated;
grant insert on public.songs to authenticated;
grant insert, delete on public.song_likes to authenticated;
grant usage, select on sequence public.songs_id_seq to authenticated;
