create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  province text not null check (province ~ '^[a-z0-9-]+$'),
  title text not null check (char_length(trim(title)) between 1 and 80),
  artist text not null check (char_length(trim(artist)) between 1 and 80),
  link text check (link is null or char_length(link) <= 500),
  submitted_by text not null default 'مهمان یلدا'
    check (char_length(trim(submitted_by)) between 1 and 50),
  likes integer not null default 0 check (likes >= 0),
  created_at timestamptz not null default now()
);

alter table public.songs enable row level security;

drop policy if exists "Public can read songs" on public.songs;
create policy "Public can read songs"
on public.songs for select
to anon, authenticated
using (true);

drop policy if exists "Public can submit songs" on public.songs;
create policy "Public can submit songs"
on public.songs for insert
to anon, authenticated
with check (
  likes = 0
  and char_length(trim(title)) between 1 and 80
  and char_length(trim(artist)) between 1 and 80
  and char_length(trim(submitted_by)) between 1 and 50
);

create or replace function public.adjust_song_likes(song_id bigint, change_by integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare new_likes integer;
begin
  if change_by not in (-1, 1) then
    raise exception 'change_by must be -1 or 1';
  end if;

  update public.songs
  set likes = greatest(0, likes + change_by)
  where id = song_id
  returning likes into new_likes;

  if new_likes is null then
    raise exception 'Song not found';
  end if;
  return new_likes;
end;
$$;

revoke all on function public.adjust_song_likes(bigint, integer) from public;
grant execute on function public.adjust_song_likes(bigint, integer) to anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.songs to anon, authenticated;
grant usage, select on sequence public.songs_id_seq to anon, authenticated;
